config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :students
  resources :users
  
  root 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :students
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

before_action :authenticate_user!



    def index
        @students=Student.all
    end

    def new
        @student=Student.new
    end

    def create
        student=Student.new(student_params)
        student.user_id = current_user.id
            if student.save
                redirect_to :action =>'index'
            else
                redirect_to :action =>'new'
            end
    end

    def show
        @student=Student.find(params[:id])
    end

    def edit
        @student=Student.find(params[:id])
    end

    def update
        student=Student.find(params[:id])
            if student.update(student_params)
                redirect_to :action=> 'show', :id => student.id
            else
                redirect_to :action=>'new'
            end
    end

    def destroy
        student=Student.find(params[:id])
        student.destroy
        redirect_to action: :index
    end

private
    def student_params
        params.require(:student).permit(:name, :profile, :mentor, :grade)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kobegeek1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
      <h1>Kobegeek1</h1>
      <div class="header-list">
      <ul>
        <a><%= link_to "ログイン", students_path %></a>
        <a><%= link_to "新規登録", new_user_registration_path %></a>
        <a><%= link_to '投稿ページへ', new_student_path%></a>
        <a><%= link_to '一覧ページへ', students_path%></a>
        <a><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></a>
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>


  </body>
</html>

app/views/students/edit.html.erb
<h2>編集ページ</h2>

<%= form_for @student do |f| %>
    
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, :size => 140 %>
    </div>

    <div class="field">
        <%= f.label :profile %>
        <%= f.text_field :profile, :size => 140 %>
    </div>

    <div class="field">
        <%= f.label :mentor %>
        <%= f.text_field :mentor, :size => 140 %>
    </div>

    <div class="field">
        <%= f.label :grade %>
        <%= f.text_field :grade, :size => 140 %>
    </div>

    <%= f.submit "編集する" %>
<% end %>

app/views/students/index.html.erb
<%= stylesheet_link_tag 'students', :media => "all" %>

<h2>投稿一覧</h2>
<br>

<div class="students-container">
    <% @students.each do |t| %>
        <div class="student">
            <p><%= t.name %></p>
            <p><%= t.profile %></p>
            <p><%= t.mentor %></p>
            <p><%= t.grade %></p>
            <p><%= t.user.email %></p>
            <p><%= link_to "詳細へ", student_path(t.id) %></p>
            <p><%= link_to "編集する", edit_student_path(t.id) %></p>
            <p><%= button_to '削除する', student_path(t.id), method: :delete%></p>
        </div>
    <% end %>
</div>

app/views/students/new.html.erb
<h1>新規投稿</h1>
<br>
<%= form_for @student do |f| %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, :size => 140 %>
    </div>
<br>
    <div class="field">
        <%= f.label :profile %>
        <%= f.text_field :profile, :size => 140 %>
    </div>
<br>
    <div class="field">
        <%= f.label :mentor %>
        <%= f.text_field :mentor, :size => 140 %>
    </div>
<br>
    <div class="field">
        <%= f.label :grade %>
        <%= f.text_field :grade, :size => 140 %>
    </div>
<br>
    <%= f.submit "投稿する" %>
<% end %>

app/views/students/show.html.erb
<h2>詳細ページ</h2>
<br>
<div class="student">
    <p><%= @student.name%></p>
    <p><%= @student.profile %></p>
    <p><%= @student.mentor %></p>
    <p><%= @student.grade %></p>
</div> 

<%= link_to '投稿ページへ', new_student_path%>
<%= link_to '一覧ページへ', students_path%>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>